AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple AWS Lambda for searching book records within a DynamoDB table.
Resources:
  GetTagsFx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/get-tags-1.0-SNAPSHOT.jar
      Handler: com.revature.get_tags.GetHandler
      Runtime: java8.al2
      Description: Java function
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
